name: deep_RL_base
channels:
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=2.1.0
  - alsa-lib=1.2.14
  - aom=3.9.1
  - astor=0.8.1
  - asttokens=3.0.0
  - astunparse=1.6.3
  - attr=2.5.1
  - blas=1.0
  - box2d-py=2.3.8
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.2.25
  - cached-property=1.5.2
  - cairo=1.18.4
  - certifi=2025.4.26
  - charset-normalizer=3.3.2
  - cloudpickle=3.1.1
  - comm=0.2.1
  - cpp-expected=1.1.0
  - cuda-crt-tools=12.4.131
  - cuda-cudart=12.4.127
  - cuda-cudart_linux-64=12.4.127
  - cuda-cupti=12.4.127
  - cuda-nvcc-tools=12.4.131
  - cuda-nvrtc=12.4.127
  - cuda-nvtx=12.4.127
  - cuda-nvvm-tools=12.4.131
  - cuda-version=12.4
  - cudnn=9.1.1.17
  - dav1d=1.2.1
  - dbus=1.13.18
  - debugpy=1.8.11
  - decorator=5.1.1
  - executing=0.8.3
  - expat=2.6.4
  - farama-notifications=0.0.4
  - flatbuffers=24.12.23
  - fluidsynth=2.3.4
  - fmt=11.0.2
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - freetype=2.13.3
  - gast=0.5.3
  - gettext=0.24.1
  - gettext-tools=0.24.1
  - giflib=5.2.2
  - glib=2.84.0
  - glib-tools=2.84.0
  - google-pasta=0.2.0
  - graphite2=1.3.14
  - grpcio=1.67.1
  - gymnasium=1.0.0
  - h5py=3.13.0
  - harfbuzz=11.0.0
  - hdf5=1.14.3
  - icu=75.1
  - idna=3.7
  - intel-openmp=2025.0.0
  - ipykernel=6.29.5
  - ipython=9.1.0
  - ipython_pygments_lexers=1.1.1
  - jack=1.9.22
  - jax-jumpy=1.0.0
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - keras=3.10.0
  - krb5=1.21.3
  - lame=3.100
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20240722.0
  - libaec=1.1.3
  - libarchive=3.7.7
  - libasprintf=0.24.1
  - libasprintf-devel=0.24.1
  - libavif16=1.3.0
  - libcap=2.71
  - libcublas=12.4.5.8
  - libcufft=11.2.1.3
  - libcurand=10.3.5.147
  - libcurl=8.11.1
  - libcusolver=11.6.1.9
  - libcusparse=12.3.1.170
  - libcxx=19.1.6
  - libcxxabi=19.1.6
  - libdb=6.2.32
  - libdeflate=1.20
  - libdrm=2.4.124
  - libedit=3.1.20230828
  - libegl=1.7.0
  - libev=4.33
  - libexpat=2.6.4
  - libffi=3.4.4
  - libflac=1.4.3
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgcrypt-lib=1.11.1
  - libgettextpo=0.24.1
  - libgettextpo-devel=0.24.1
  - libgfortran-ng=8.2.0
  - libgfortran5=14.2.0
  - libgl=1.7.0
  - libglib=2.84.0
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=14.2.0
  - libgpg-error=1.55
  - libgrpc=1.67.1
  - libiconv=1.18
  - libjpeg-turbo=3.0.3
  - libmad=0.15.1b
  - libmamba=2.0.5
  - libmpdec=4.0.0
  - libnghttp2=1.64.0
  - libnsl=2.0.1
  - libnvjitlink=12.4.127
  - libogg=1.3.5
  - libopenblas=0.3.21
  - libopus=1.3.1
  - libpciaccess=0.18
  - libpng=1.6.47
  - libprotobuf=5.28.3
  - libre2-11=2024.07.02
  - libsndfile=1.2.2
  - libsodium=1.0.18
  - libsolv=0.7.30
  - libsqlite=3.49.2
  - libssh2=1.11.1
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libsystemd0=256.9
  - libtiff=4.6.0
  - libudev1=257.4
  - libunwind=1.6.2
  - liburing=2.9
  - libusb=1.0.28
  - libuuid=2.38.1
  - libvorbis=1.3.7
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.8.0
  - libxml2=2.13.5
  - libzlib=1.3.1
  - llvm-openmp=20.1.5
  - lz4-c=1.9.4
  - lzo=2.10
  - mamba=2.0.5
  - markdown=3.4.1
  - markdown-it-py=2.2.0
  - markupsafe=2.1.3
  - matplotlib-inline=0.1.6
  - mdurl=0.1.0
  - mkl=2023.2.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - ml_dtypes=0.4.1
  - mpg123=1.32.9
  - namex=0.0.7
  - nccl=2.21.5.1
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - nlohmann_json=3.11.3
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openssl=3.4.0
  - opt_einsum=3.3.0
  - optree=0.12.1
  - opusfile=0.12
  - packaging=24.2
  - parso=0.8.4
  - pcre2=10.44
  - pexpect=4.8.0
  - pip=24.2
  - pixman=0.46.0
  - platformdirs=4.3.7
  - portaudio=19.6.0
  - portmidi=2.0.4
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - protobuf=5.28.3
  - psutil=5.9.0
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pulseaudio-client=17.0
  - pure_eval=0.2.2
  - pygame=2.6.1
  - pygments=2.15.1
  - pysocks=1.7.1
  - python=3.12.2
  - python-dateutil=2.9.0post0
  - python-flatbuffers=24.3.25
  - python_abi=3.12
  - pyzmq=26.2.0
  - rav1e=0.7.1
  - re2=2024.07.02
  - readline=8.2
  - reproc=14.2.5.post0
  - reproc-cpp=14.2.5.post0
  - requests=2.32.3
  - rich=13.9.4
  - sdl2=2.32.50
  - sdl2_image=2.8.2
  - sdl2_mixer=2.6.3
  - sdl2_ttf=2.24.0
  - sdl3=3.2.8
  - setuptools=75.1.0
  - simdjson=3.11.3
  - six=1.16.0
  - snappy=1.2.1
  - spdlog=1.15.0
  - stack_data=0.2.0
  - svt-av1=3.0.2
  - tbb=2021.8.0
  - tensorboard=2.18.0
  - tensorboard-data-server=0.7.0
  - tensorflow=2.18.0
  - tensorflow-base=2.18.0
  - tensorflow-estimator=2.18.0
  - termcolor=2.1.0
  - tk=8.6.13
  - tornado=6.5
  - traitlets=5.14.3
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2024b
  - urllib3=2.2.3
  - wayland=1.23.1
  - wcwidth=0.2.5
  - werkzeug=3.0.6
  - wheel=0.44.0
  - wrapt=1.14.1
  - xkeyboard-config=2.44
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcursor=1.2.3
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxrender=0.9.12
  - xorg-libxscrnsaver=1.2.4
  - xorg-xorgproto=2024.1
  - xz=5.4.6
  - yaml-cpp=0.8.0
  - zeromq=4.3.5
  - zlib=1.3.1
  - zstd=1.5.7
