name: deep_RL_base
channels:
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=2.1.0
  - astunparse=1.6.3
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.11.26
  - certifi=2024.12.14
  - charset-normalizer=3.3.2
  - cpp-expected=1.1.0
  - cuda-crt-tools=12.4.131
  - cuda-cudart=12.4.127
  - cuda-cudart_linux-64=12.4.127
  - cuda-cupti=12.4.127
  - cuda-nvcc-tools=12.4.131
  - cuda-nvrtc=12.4.127
  - cuda-nvtx=12.4.127
  - cuda-nvvm-tools=12.4.131
  - cuda-version=12.4
  - cudnn=9.1.1.17
  - expat=2.6.4
  - flatbuffers=24.3.25
  - fmt=11.0.2
  - gast=0.5.3
  - giflib=5.2.2
  - google-pasta=0.2.0
  - grpcio=1.62.2
  - h5py=3.12.1
  - hdf5=1.12.1
  - icu=73.1
  - idna=3.7
  - intel-openmp=2023.1.0
  - jpeg=9e
  - keras=3.6.0
  - krb5=1.20.1
  - ld_impl_linux-64=2.40
  - libabseil=20240116.2
  - libarchive=3.7.7
  - libcublas=12.4.5.8
  - libcufft=11.2.1.3
  - libcurand=10.3.5.147
  - libcurl=8.11.1
  - libcusolver=11.6.1.9
  - libcusparse=12.3.1.170
  - libcxx=19.1.6
  - libcxxabi=19.1.6
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=14.2.0
  - libgrpc=1.62.2
  - libiconv=1.16
  - libmamba=2.0.5
  - libmpdec=4.0.0
  - libnghttp2=1.57.0
  - libnvjitlink=12.4.127
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libprotobuf=4.25.3
  - libsodium=1.0.18
  - libsolv=0.7.30
  - libssh2=1.11.1
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libuuid=1.41.5
  - libxml2=2.13.5
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - mamba=2.0.5
  - markdown=3.4.1
  - markdown-it-py=2.2.0
  - markupsafe=2.1.3
  - mdurl=0.1.0
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - ml_dtypes=0.4.0
  - namex=0.0.7
  - nccl=2.21.5.1
  - ncurses=6.4
  - nlohmann_json=3.11.3
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openssl=3.4.0
  - opt_einsum=3.3.0
  - optree=0.12.1
  - packaging=24.2
  - pcre2=10.42
  - pip=24.2
  - protobuf=4.25.3
  - pygments=2.15.1
  - pysocks=1.7.1
  - python=3.12.8
  - python-flatbuffers=24.3.25
  - re2=2022.04.01
  - readline=8.2
  - reproc=14.2.5.post0
  - reproc-cpp=14.2.5.post0
  - requests=2.32.3
  - rich=13.9.4
  - setuptools=75.1.0
  - simdjson=3.11.3
  - six=1.16.0
  - snappy=1.2.1
  - spdlog=1.15.0
  - sqlite=3.45.3
  - tbb=2021.8.0
  - tensorboard=2.17.0
  - tensorboard-data-server=0.7.0
  - tensorflow=2.17.0
  - tensorflow-base=2.17.0
  - tensorflow-estimator=2.17.0
  - termcolor=2.1.0
  - tk=8.6.14
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2024b
  - urllib3=2.2.3
  - werkzeug=3.0.6
  - wheel=0.44.0
  - wrapt=1.14.1
  - xz=5.4.6
  - yaml-cpp=0.8.0
  - zeromq=4.3.5
  - zlib=1.2.13
  - zstd=1.5.6
